version: '3'
services:
  app-server:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: user-flow-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}     
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}     
    volumes:
      - ./mongo-data:/data/db
